site_name: Coding Cleverly
site_url: https://www.example.com  # Update with your website URL
# [![Coding Cleverly](docs/logo.png)](#)

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  extra_css:
  - custom/theme.css
  - custom/assets/logo.css


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/CodingCleverly
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CodingCleverly
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/HarisIftikhar1/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/CodingCleverly"  target="_blank" rel="noopener">Coding Cleverly</a>
  

nav:
  - Home: index.md  # Update with your home page file
  - Tutorials:
      - Getting Started: tutorials.md
      - Advanced Techniques: tutorials/advanced-techniques.md
  - Blog:
      - Latest Posts: blogs.md
      - Archives: blog/archives.md
  - About: about.md  # Update with your about page file

# Customize the appearance and content of the sidebar
sidebar:
  - Home: index.md
  - Tutorials:
      - Getting Started: tutorials/getting-started.md
      - Advanced Techniques: tutorials/advanced-techniques.md
  - Blog:
      - Latest Posts: blog/latest.md
      - Archives: blog/archives.md
  - Social Media:
      - GitHub: https://github.com/CodingCleverly
      - Twitter: https://twitter.com/CodingCleverly
      - LinkedIn: https://www.linkedin.com/in/HarisIftikhar1/

# Configure the appearance and content of the footer
footer:
  - '&#169; 2023 <a href="https://github.com/CodingCleverly" target="_blank" rel="noopener">Coding Cleverly</a>'

# Add any custom settings
